/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class over6_over6client_MainActivity */

#ifndef _Included_over6_over6client_MainActivity
#define _Included_over6_over6client_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     over6_over6client_MainActivity
 * Method:    StringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_over6_over6client_MainActivity_StringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
